version: "2"
services:
  web:
    build: .
    command: npm run watch dev
    volumes:
      - .:/app/
    ports:
      - "3001:3001"
    links:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'